### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by lhy007123** [shack2/SNETCracker#15]
I don't know how to use this, there's no executable file.

**Comment by huitc** [comment]
u want this? https://github.com/shack2/SNETCracker/releases

**Comment by lhy007123** [comment]
> 你想要这个吗？https://github.com/shack2/SNETCracker/releases

what's this?

**Comment by lhy007123** [comment]
> 你想要这个吗？https://github.com/shack2/SNETCracker/releases

what's this?

**Comment by lhy007123** [comment]
> u want this? https://github.com/shack2/SNETCracker/releases

yeah,I want this.thank you!but why am I not having an executable file in master of branch
