### ISSUE TITLE
程序长时间运行，不释放内存，最终占满内存报错“System.OutOfMemoryException”

### ISSUE THREAD

**Issue by zhangketong** [shack2/SNETCracker#20]
![image](https://user-images.githubusercontent.com/55721676/65471421-9ad10000-dea1-11e9-980b-6239bbc49457.png)
我是用Beta28 20190715版本。当运行很多各IP扫描时，发现扫描程序所占用的内存不断增加没有回收，最终物理内存被占满，程序奔溃退出。大神能否改下版本解决。

**Comment by shack2** [comment]
IP不要太多，所有任务队列都要先创建存到内存中在运行，如果太多，可能内存就会崩溃。
