### ISSUE TITLE
各种出错

### ISSUE THREAD

**Issue by hatvgit** [shack2/SNETCracker#6]
SSH登录发生异常！Could not load file or assembly 'ChilkatDotNet4.dll' or one of its dependencies. 找不到指定的模块。   at SNETCracker.Model.CrackSSH.creack(String ip, Int32 port, String username, String password, Int32 timeOut)

:3389-RDP操作异常-Unable to get the window handle for the 'RdpClient' control. Windowless ActiveX controls are not supported.

**Comment by shack2** [comment]
SSH登录发生异常！Could not load file or assembly 'ChilkatDotNet4.dll' or one of its dependencies. 找不到指定的模块。这个错误是因为需要这个ssh模块需要vc++2010 32位得支持，下载安装就行了。rdp得错误一般是线程过多，一般建议最好在20个以内，自己慢慢试，线程多了就会出问题。

**Comment by bcdlbgm** [comment]
我导入文件都会卡 文件不大
卡死........

**Comment by xatu2007** [comment]
RDP操作异常-无法获取“RdpClient”控件的窗口句柄。不支持无窗口的 ActiveX 控件。
这个一般是什么错误？

**Comment by shack2** [comment]
看手册rdp需要10个以下线程，才不容易报错。------------------ 原始邮件 ------------------
发件人: "xatu2007"<notifications@github.com>
发送时间: 2019年6月16日(星期天) 凌晨1:20
收件人: "shack2/SNETCracker"<SNETCracker@noreply.github.com>;
抄送: "shack2"<1341413415@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [shack2/SNETCracker] 各种出错 (#6)



RDP操作异常-无法获取“RdpClient”控&#x4EF6;的窗口句柄。不支持无窗口的 ActiveX 控&#x4EF6;。
 这个一般是什么错误？
 
&mdash;

**Comment by shack2** [comment]
20190713版本已经修复RDP异常问题。
